teleport:
  check_every_n_ticks: 20
  overworld_to_end:
    from: 330
    to: 5
  end_to_overworld:
    from: -5
    to: 320
items:
  spawn_pearl:
    trigger: right_click
    name: Spawn Pearl
    consume: true
    commands:
      - execute as {{player}} in minecraft:overworld run tp 0 64 0
      - say {{player}} teleported to spawn
  potato:
    trigger: eat
    name: Teleportato
    commands:
      - execute as {{player}} in minecraft:overworld run tp 0 64 0
      - say {{player}} teleported to spawn
