items:
  spawn_pearl:
    trigger: right_click
    name: Spawn Pearl
    consume: true
    commands:
      - execute as {{player}} in minecraft:overworld run tp 0 64 0
      - say {{player}} teleported to spawn
  potato:
    trigger: eat
    name: Teleportato
    commands:
      - execute as {{player}} in minecraft:overworld run tp 0 64 0
      - say {{player}} teleported to spawn