main: fallen.pentagon.know2good.Know2Good
name: Know2Good
version: "0.3.0-SNAPSHOT"
api-version: "1.15"
commands:
  reload:
    usage: /know2good:reload
    permission: know2good.reload
    permission-message: You don't have permission for that.